# Generated by Django 5.2.6 on 2025-11-15 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0002_tagsreceita_user_atualizado_em_user_bio_user_cidade_and_more'),
        ('receitas', '0004_seguidor'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='receitas', to='autenticacao.tagsreceita'),
        ),
    ]
