# Generated by Django 5.2.6 on 2025-11-21 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0005_receita_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='imagem',
            field=models.ImageField(blank=True, help_text='Imagem ilustrativa da receita (opcional).', null=True, upload_to='receitas/'),
        ),
    ]
