# Generated by Django 5.2.8 on 2025-11-20 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0002_tagsreceita_user_atualizado_em_user_bio_user_cidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='openai_api_key_encrypted',
            field=models.TextField(blank=True, null=True, verbose_name='OpenAI API Key (Encrypted)'),
        ),
    ]
